# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: zh-CN
title: "Hybrid Theory"
description: "Technical Blog, Blockchain, Distributed System, Transaction Processing, Database."
baseurl: # the subpath of your site, e.g. "/blog"
url: https://www.hytheory.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: /images/logo.svg # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 150 # 200
mathjax: true # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-123706837-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: hybridtheory # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: PangShuaifeng # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Marty Pang
  picture: /images/profile.png
  email: pang.shuaifeng@gmail.com
  twitter: PangShuaifeng
  links:
    - title: Instagram
      url: https://instagram.com/_pssssssssf
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/martypang
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/_pssssssssf
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/martypang
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
